on:
    workflow_call:
      inputs:
        tag:
          type: string
          required: true
          description: image tag
        context:
          type: string
          required: true
          description: docker build context
        platforms:
            type: string
            required: true
            description: docker buildx platforms

concurrency:
    group: ${{ inputs.tag }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up Docker
                uses: crazy-max/ghaction-setup-docker@v3
                with:
                  daemon-config: |
                    {
                      "debug": true,
                      "features": {
                        "containerd-snapshotter": true
                      }
                    }            
        

            -   name: Log in to the container registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for docker
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ github.repository }}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    install: true
                    platforms: ${{ inputs.platforms }}

            -   name: Build and push docker image
                uses: docker/build-push-action@v6
                with:
                    push: true
                    load: true
                    tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.tag }}
                    context: ${{ inputs.context }}
                    platforms: ${{ inputs.platforms }}
